/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesRouteImport } from './routes/files'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FileFileIdRouteImport } from './routes/file.$fileId'
import { Route as PacketFileIdRouteImport } from './routes/packet.$fileId'
import { Route as WatchWatchKeyRouteImport } from './routes/watch.$watchKey'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMailWebhookRouteImport } from './routes/api/mail/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FileFileIdRoute = FileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketFileIdRoute = PacketFileIdRouteImport.update({
  id: '/packet/$fileId',
  path: '/packet/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchWatchKeyRoute = WatchWatchKeyRouteImport.update({
  id: '/watch/$watchKey',
  path: '/watch/$watchKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailWebhookRoute = ApiMailWebhookRouteImport.update({
  id: '/api/mail/webhook',
  path: '/api/mail/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/packet/$fileId': typeof PacketFileIdRoute
  '/watch/$watchKey': typeof WatchWatchKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/webhook': typeof ApiMailWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/packet/$fileId': typeof PacketFileIdRoute
  '/watch/$watchKey': typeof WatchWatchKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/webhook': typeof ApiMailWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/packet/$fileId': typeof PacketFileIdRoute
  '/watch/$watchKey': typeof WatchWatchKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/webhook': typeof ApiMailWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/login'
    | '/file/$fileId'
    | '/packet/$fileId'
    | '/watch/$watchKey'
    | '/api/auth/$'
    | '/api/mail/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/login'
    | '/file/$fileId'
    | '/packet/$fileId'
    | '/watch/$watchKey'
    | '/api/auth/$'
    | '/api/mail/webhook'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/login'
    | '/file/$fileId'
    | '/packet/$fileId'
    | '/watch/$watchKey'
    | '/api/auth/$'
    | '/api/mail/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  FileFileIdRoute: typeof FileFileIdRoute
  PacketFileIdRoute: typeof PacketFileIdRoute
  WatchWatchKeyRoute: typeof WatchWatchKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMailWebhookRoute: typeof ApiMailWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$fileId': {
      id: '/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/file/$fileId'
      preLoaderRoute: typeof FileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet/$fileId': {
      id: '/packet/$fileId'
      path: '/packet/$fileId'
      fullPath: '/packet/$fileId'
      preLoaderRoute: typeof PacketFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$watchKey': {
      id: '/watch/$watchKey'
      path: '/watch/$watchKey'
      fullPath: '/watch/$watchKey'
      preLoaderRoute: typeof WatchWatchKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/webhook': {
      id: '/api/mail/webhook'
      path: '/api/mail/webhook'
      fullPath: '/api/mail/webhook'
      preLoaderRoute: typeof ApiMailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  FileFileIdRoute: FileFileIdRoute,
  PacketFileIdRoute: PacketFileIdRoute,
  WatchWatchKeyRoute: WatchWatchKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMailWebhookRoute: ApiMailWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
